name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest


    steps:
    - name: Install Crystal 1.9.0
      run: |
        Invoke-WebRequest -Uri https://github.com/crystal-lang/crystal/releases/download/1.9.0/crystal-1.9.0-windows-x86_64-msvc-unsupported.exe -OutFile crystal-1.9.0-windows-x86_64-msvc-unsupported.exe
        .\crystal-1.9.0-windows-x86_64-msvc-unsupported.exe /verysilent
    - name: crystal version
      run: crystal version
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
