name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest


    steps:
    - name: Scoop Installer
      uses: MinoruSekine/setup-scoop@main
    - name: Scoop Bucket Add
      run: scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
    - name: Scoop Crystal Install
      run: scoop install crystal
    - uses: actions/checkout@v3
    - name: crystal version
      run: crystal version
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
