name: Crystal CI

on:
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Crystal 1.9.0
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://github.com/crystal-lang/crystal/releases/download/1.9.0/crystal-1.9.0-windows-x86_64-msvc-unsupported.exe -OutFile crystal-1.9.0-windows-x86_64-msvc-unsupported.exe
        & ".\crystal-1.9.0-windows-x86_64-msvc-unsupported.exe" /verysilent
        dir 'C:\Program Files\Crystal'
    - name: crystal version
      shell: pwsh
      run: |
        & 'C:\Program Files\Crystal\crystal.exe' version
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: pwsh
      run: |
        & 'C:\Program Files\Crystal\shards.exe' install
    - name: Run tests
      shell: pwsh
      run: |
        & 'C:\Program Files\Crystal\crystal.exe' spec
